### ISSUE TITLE
Extracting the unmapped fields in separate JSON

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-flux#1]
While there is a fix-function `map(_else)` to take over all unmapped elements of a dataset, these elements are transferred to the same JSON file as all mapped elements.

Since both mapped and unmapped elements are in the same JSON-file it is difficult to read and to distinguish between them quickly.

A module would be great that creates a separate JSON with all unmapped elements.
Instead of a new module an alternative way would be if the fix-function `map(_else)` already triggers the creation of the separate JSON file.

**Comment by dr0i** [comment]
You could use a TeePipe to teepipe the input into 2 morph's, one of these morph's would  consist of only the '_else' and the other with all the rules but without the '_else'. The output goes into 2 different sinks.

**Comment by dr0i** [comment]
Addendum: the one morph with the '_else' had to include the other morph ('<xi:include href="morph-with-the-rules.xml"/>')  of course.

**Comment by TobiasNx** [comment]
Closing, since not related to the extension
