### ISSUE TITLE
Open VSX Listing: Sign the Publisher Agreement, package the license

### ISSUE THREAD

**Issue by spoenemann** [metafacture/metafacture-flux#8]
See https://github.com/metafacture/metafacture-fix/issues/41 for details.

The Publisher Agreement must be signed only once for each publisher (@katauber), but the license must be properly packaged with every extension.

**Comment by katauber** [comment]
Extension must be published into [Open VSX Registry](https://open-vsx.org/) after merging, because the extension is build after merging into master.
